### ISSUE TITLE
Make VoiceOver + list-style-type: none; play nice

### ISSUE THREAD

**Issue by Kilian** [erikkroes/access-tools#22]
```css
li::before {
	content: "\200B"; /* Make VoiceOver + list-style-type: none; play nice */
	position: absolute;
}
```
By Peter van Grieken
